function validateIP(IPvalue){errorString="";theName="IPaddress";var ipPattern=/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;var ipArray=IPvalue.match(ipPattern);if(IPvalue=="0.0.0.0")
errorString=errorString+theName+': '+IPvalue+' is a special IP address and cannot be used here.';else if(IPvalue=="255.255.255.255")
errorString=errorString+theName+': '+IPvalue+' is a special IP address and cannot be used here.';if(ipArray==null)
errorString=errorString+theName+': '+IPvalue+' is not a valid IP address.';else{for(i=0;i<4;i++){thisSegment=ipArray[i];if(thisSegment>255){errorString=errorString+theName+': '+IPvalue+' is not a valid IP address.';i=4;}
if((i==0)&&(thisSegment>255)){errorString=errorString+theName+': '+IPvalue+' is a special IP address and cannot be used here.';i=4;}}}
extensionLength=3;if(errorString=="")
return("That is a valid IP address.");else
return(errorString);}
delHost=function(dataStore,gridPanel){var u=gridPanel.getSelections();if(u.length<1)return(false);Ext.MessageBox.confirm('Message','Are you sure you want to delete this/these host(s)?',function(btn){if(btn!="yes")return(false);for(i=0;i<u.length;i++){Ext.Ajax.request({url:'/host/delete',failure:function(data){var action=Ext.util.JSON.decode(data.responseText);Ext.MessageBox.alert('Error',action.info);},success:function(data){var action=Ext.util.JSON.decode(data.responseText);rx=new RegExp(action.uid,"g");var i=gridPanel.getStore().find('hostname',rx);if(i>0){gridPanel.getSelectionModel().selectRow(i);var u=gridPanel.getSelectionModel().getSelected();dataStore.remove(u);}
Ext.MessageBox.alert('Confirmation',action.info);},params:{hostname:u[i].get('hostname'),ip:u[i].get('ip')}});}});}
addHost=function(dataStore,selectedRow){Ext.apply(Ext.form.VTypes,{ipaddress:function(value,field){var x=validateIP(value);if(x=="That is a valid IP address.")return(true);this.ipaddressText=x;return(false);},ipaddressText:'Please enter a valid IP Address',});Ext.apply(Ext.form.VTypes,{hostname:function(value,field){var x=value.match(/^\w+([\.-]?\w+)*$/);if(x)
this.hostnameText="Hostname OK";else
this.hostnameText="Invalid hostname";return(x);},hostnameText:'Please enter a valid hostname',});var hostname=new Ext.form.TextField({fieldLabel:'Main hostname',allowBlank:false,name:'hostname',anchor:'90%',vtype:'hostname',});var ip=new Ext.form.TextField({fieldLabel:'IP Address',allowBlank:true,name:'ip',anchor:'90%',vtype:'ipaddress',});var aliases=new Ext.form.TextField({fieldLabel:'Name alias',allowBlank:true,name:'aliases',emptyText:'ie: webserver,mailserver,redbox',qtip:'Comma separeted list of other names this server is known as',anchor:'90%',});var formPanel=new Ext.form.FormPanel({baseCls:'x-plain',labelWidth:100,url:'/host/add',method:'GET',defaultType:'textfield',items:[hostname,ip,aliases]});var window=new Ext.Window({title:'Add New Host to LDAP',width:500,height:200,minWidth:300,minHeight:250,layout:'fit',plain:true,bodyStyle:'padding:5px;',buttonAlign:'center',items:formPanel,buttons:[{text:'Save',handler:function(){if(formPanel.form.isValid()){formPanel.form.submit({waitMsg:'Saving...',failure:function(form,action){Ext.MessageBox.alert('Error Message',action.result.info);},success:function(form,action){Ext.MessageBox.alert('Confirm',action.result.info);window.destroy();loadHostsGrid();}});}else{Ext.MessageBox.alert('Errors','Please fix the errors noted.');}}},{text:'Cancel',handler:function(){window.destroy();}}]});window.show();if(selectedRow){Ext.Ajax.request({url:'/host/get',method:'GET',disableCaching:true,params:{hostname:selectedRow.get('hostname')},success:function(data){var sudoer=Ext.util.JSON.decode(data.responseText);hostname.setValue(sudoer.hostname);hostname.setDisabled(true);ip.setValue(sudoer.ip);aliases.setValue(sudoer.aliases);formPanel.getForm()['url']='/host/update';formPanel.getForm().baseParams={'hostname':sudoer.hostname};},});}};
