delSudoRole=function(dataStore,gridPanel){var u=gridPanel.getSelections();if(u.length<1)return(false);Ext.MessageBox.confirm('Message','Are you sure you want to delete this/these role(s)?',function(btn){if(btn!="yes")return(false);for(i=0;i<u.length;i++){Ext.Ajax.request({url:'/sudo/delete',failure:function(data){var action=Ext.util.JSON.decode(data.responseText);Ext.MessageBox.alert('Error',action.info);},success:function(data){var action=Ext.util.JSON.decode(data.responseText);rx=new RegExp(action.role,"g");var i=gridPanel.getStore().find('sudorole',rx);if(i>0){gridPanel.getSelectionModel().selectRow(i);var u=gridPanel.getSelectionModel().getSelected();dataStore.remove(u);}
Ext.MessageBox.alert('Confirmation',action.info);},params:{sudorole:u[i].get('sudorole')}});}});}
addSudoRole=function(dataStore,selectedRow){var sudorole=new Ext.form.TextField({fieldLabel:'Role Name',allowBlank:false,name:'role',anchor:'90%'});var sudohost=new Ext.form.TextField({fieldLabel:'Sudo Host',allowBlank:true,name:'sudohost',value:'ALL',anchor:'90%',});var sudouser=new Ext.form.ComboBox({emptyText:'Select the user...',mode:'remote',triggerAction:'all',selectOnFocus:true,forceSelection:true,allowBlank:true,fieldLabel:'Sudo User',displayField:'uid',id:'uid',anchor:'90%',typeAhead:true,name:'sudouser',store:new Ext.data.JsonStore({url:"/user/list",root:'results',id:'gid',fields:[{name:'uid'},{name:'firstname'},{name:'surname'}],})});var sudogroup=new Ext.form.ComboBox({emptyText:'Select the group...',mode:'remote',triggerAction:'all',selectOnFocus:true,forceSelection:true,allowBlank:true,fieldLabel:'Sudo Group',displayField:'name',id:'gid',anchor:'90%',typeAhead:true,name:'sudogroup',store:new Ext.data.JsonStore({url:"/group/list",root:'results',id:'gid',fields:[{name:'gid'},{name:'name'}],})});var sudoCommandRecord=new Ext.data.Record.create({fields:[{name:'command',type:'string'}]});var sudoCommandsStore=new Ext.data.Store({fields:[{name:'command'}]});var sudoCommandsColumns=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{header:"Command",width:'100%',dataIndex:'command'},]);function addCommand(store){Ext.Msg.prompt('Command','Please enter a new command (ie: /bin/bash):',function(btn,text){if(btn=='ok'){var k=new sudoCommandRecord({command:text,});store.insert(0,k);}});}
var sudoCommandsGrid=new Ext.grid.GridPanel({store:sudoCommandsStore,deferredRender:false,cm:sudoCommandsColumns,sm:new Ext.grid.RowSelectionModel({singleSelect:false}),width:'100%',height:150,frame:true,iconCls:'icon-grid',name:'sudocommand',id:'sudocommand',tbar:[{text:'Add Command',tooltip:'Add a new command to this role',iconCls:'add',handler:function(){addCommand(sudoCommandsStore);return(true);},},'-',{text:'Remove Command',tooltip:'Remove the selected command from this role',iconCls:'remove',handler:function(){var rec=sudoCommandsGrid.getSelectionModel().getSelections();for(x=0;x<rec.length;x++)
if(rec[x])sudoCommandsStore.remove(rec[x]);return(true);},}],});var sudoOptionRecord=new Ext.data.Record.create({fields:[{name:'sudooption',type:'string'}]});var sudoOptionsStore=new Ext.data.Store({fields:[{name:'sudooption'}]});var sudoOptionsColumns=new Ext.grid.ColumnModel([new Ext.grid.RowNumberer(),{header:"Option",width:'100%',dataIndex:'sudooption'},]);function addOption(store){Ext.Msg.prompt('Option','Please enter a new option (ie: timestamp_timeout=30):',function(btn,text){if(btn=='ok'){var k=new sudoOptionRecord({sudooption:text,});store.insert(0,k);}});}
var sudoOptionsGrid=new Ext.grid.GridPanel({store:sudoOptionsStore,deferredRender:false,cm:sudoOptionsColumns,sm:new Ext.grid.RowSelectionModel({singleSelect:false}),width:'90%',height:150,frame:true,iconCls:'icon-grid',name:'sudooption',id:'sudooption',tbar:[{text:'Add Option',tooltip:'Add a new option to this role',iconCls:'add',handler:function(){addOption(sudoOptionsStore);return(true);},},'-',{text:'Remove Option',tooltip:'Remove the selected option from this role',iconCls:'remove',handler:function(){var rec=sudoOptionsGrid.getSelectionModel().getSelections();for(x=0;x<rec.length;x++)
if(rec[x])sudoOptionsStore.remove(rec[x]);return(true);},},'-',{text:'Options Help',tooltip:'Display available options',iconCls:'options',handler:function(){Ext.MessageBox.alert('Information','Please visit <a target=_blank href="http://www.gratisoft.us/sudo/man/sudoers.html#sudoers_options">Sudo</a> project page');return(true);},}],});var formPanel=new Ext.form.FormPanel({baseCls:'x-plain',labelWidth:100,url:'/sudo/add',method:'GET',defaultType:'textfield',items:[sudorole,sudohost,sudouser,sudogroup,sudoCommandsGrid,sudoOptionsGrid]});var window=new Ext.Window({title:'Add New Sudo Role to LDAP',width:500,height:480,minWidth:350,minHeight:420,layout:'fit',plain:true,bodyStyle:'padding:5px;',buttonAlign:'center',items:formPanel,buttons:[{text:'Save',handler:function(){if(formPanel.form.isValid()){sudoCommandsGrid.getSelectionModel().selectAll();var commands='';var commandsList=sudoCommandsGrid.getSelections();for(i=0;i<commandsList.length;i++){commands+=commandsList[i].get('command')+";";}
var sudoOptions='';sudoOptionsGrid.getSelectionModel().selectAll();var sudoOptionsList=sudoOptionsGrid.getSelections();for(i=0;i<sudoOptionsList.length;i++){sudoOptions+=sudoOptionsList[i].get('sudooption')+";";}
formPanel.form.submit({waitMsg:'Saving...',params:{'sudocommands':commands,'sudooptions':sudoOptions},failure:function(form,action){Ext.MessageBox.alert('Error Message',action.result.info);},success:function(form,action){Ext.MessageBox.alert('Confirm',action.result.info);window.destroy();loadSudoGrid();}});}else{Ext.MessageBox.alert('Errors','Please fix the errors noted.');}}},{text:'Cancel',handler:function(){window.destroy();}}]});window.show();if(selectedRow){Ext.Ajax.request({url:'/sudo/get',method:'GET',disableCaching:true,params:{sudorole:selectedRow.get('sudorole')},success:function(data){var sudoer=Ext.util.JSON.decode(data.responseText);sudorole.setValue(sudoer.cn);sudorole.setDisabled(true);sudohost.setValue(sudoer.sudoHost);if(sudoer.sudoUser.indexOf("%")==-1)
sudouser.setValue(sudoer.sudoUser);else
sudogroup.setValue(sudoer.sudoUser);var commands=sudoer.sudoCommand.split(";");if(!isArray(commands)){commands=new Array(commands);}
for(i=0;i<commands.length;i++){var k=new sudoCommandRecord({command:commands[i],});sudoCommandsStore.insert(0,k);}
var options=sudoer.sudoOption.split(";");if(!isArray(options)){options=new Array(options);}
for(i=0;i<options.length;i++){var k=new sudoOptionRecord({sudooption:options[i],});sudoOptionsStore.insert(0,k);}
formPanel.getForm()['url']='/sudo/update';formPanel.getForm().baseParams={'role':sudoer.cn};},});}};
